[workspace]
members = ["core"]

[package]
name = "gameroy"
version = "0.1.0"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
embed-resource = "1.7.1"

[dependencies]

gameroy-core = { path = "core" }
crui = { path = "../crui", features=["simple_shaping"] }
sprite-render = { path = "../sprite-render-rs", features=["opengl"] }
audio-engine = { path = "../audio-engine"}
winit = { version = "0.26.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
ron = "0.6"
image = "0.23"
parking_lot = "0.11"
env_logger = "0.9.0"
log = "0.4.14"
clap = "3.1.5"
once_cell = "1.10.0"
toml = "0.5.8"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[profile.test]
opt-level = 3

[profile.dev.package.audio-engine]
opt-level = 3
# overflow-checks = false
