[workspace]
members = ["core", "jit", "gameroy", "android", "native", "wasm", "libretro", "web/gameroy-vite"]
resolver = "2"

[workspace.package]
version = "0.3.1"
edition = "2021"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
repository = "https://github.com/Rodrigodd/gameroy"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1
[profile.dev.package.audio-engine]
opt-level = 3

# Make image decoding be about 10x faster.
[profile.dev.package.image]
opt-level = 3
[profile.dev.package.png]
opt-level = 3
[profile.dev.package.miniz_oxide]
opt-level = 3
[profile.dev.package.flate2]
opt-level = 3

[profile.release]
debug = true

[profile.test]
opt-level = 3
# overflow-checks = false

[profile.fast]
inherits = "release"
debug = false
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.debugging]
inherits = "dev"
opt-level = 0

[patch.crates-io]

# waiting for https://github.com/sebcrozet/instant/pull/46
instant = { git = "https://github.com/Rodrigodd/instant.git" }

# contains hacky workaround for https://github.com/rust-windowing/winit/issues/2299
# and this volume buttons fix: https://github.com/rust-windowing/winit/pull/1919
# winit = { git = "https://github.com/Rodrigodd/winit.git", branch = "v0.27.5-gameroy" }

# fork contains a android backend
rfd = { git = "https://github.com/Rodrigodd/rfd.git", branch = "android", optional = true }

# hard code oboe's performance mode to low latency
cpal = { git = "https://github.com/Rodrigodd/cpal.git", branch = "oboe-low-latency" }

# contains this fix: https://github.com/Nercury/android_logger-rs/pull/62
android_logger = { git = "https://github.com/TiggeZaki/android_logger-rs", branch = "patch-1" }
