[workspace]
members = ["core"]

[package]
name = "gameroy"
version = "0.1.0"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gameroy-core = { path = "core" }
crui = { path = "../crui" }
sprite-render = { path = "../sprite-render-rs", features=["opengl"] }
winit = "0.24"


[profile.test]
opt-level = 3
