[workspace]
members = ["core"]

[package]
name = "gameroy"
version = "0.1.0"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gameroy-core = { path = "core" }
crui = { path = "../crui", features=["simple_shaping"] }
sprite-render = { path = "../sprite-render-rs", features=["opengl"] }
audio-engine = { path = "../audio-engine"}
winit = "0.26"
serde = { version = "1", features = ["derive"] }
ron = "0.6"
image = "0.23"
parking_lot = "0.11"
env_logger = "0.9.0"
log = "0.4.14"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[profile.test]
opt-level = 3

[profile.dev.package.audio-engine]
opt-level = 3
# overflow-checks = false
