[workspace]
members = ["core"]

[package]
name = "gameroy"
version = "0.1.0"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
embed-resource = "1.7.1"

[features]

# Enables console output.
# On windows, a application with console subsystem opens a terminal at startup, wich is undesirable
console = ["env_logger"]

default = ["console"]

[dependencies]

gameroy-core = { path = "core" }
giui = { path = "../giui", features=["simple_shaping"] }
# sprite-render = { path = "../sprite-render-rs", features=["opengl"] }
sprite-render = { features=["opengl"], rev = "7d70588bbf31f06150d7f499f315c6e9c8b13c69", git = "https://github.com/Rodrigodd/sprite-render-rs" }
# audio-engine = { path = "../audio-engine"}
audio-engine = "0.1"
winit = { version = "0.26.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
ron = "0.6"
image = { version = "0.24.1", default-features = false, features=["png"] }
parking_lot = "0.11"
env_logger = { version =  "0.9.0", optional = true }
log = "0.4.14"
clap = "3.1.5"
once_cell = "1.10.0"
toml = "0.5.8"
rfd = "0.8.1"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[profile.test]
opt-level = 3

[profile.dev.package.audio-engine]
opt-level = 3
# overflow-checks = false
