start_in_debug = false
rom_folder = "roms"

[keymap]

# KeyCode names came from this list: https://docs.rs/winit/0.26.1/winit/event/enum.VirtualKeyCode.html

left = "Left"
rigth = "Rigth"
up = "Up"
down = "Down"

a = "A"
b = "S"
select = "Back"
start = "Return"

speed = "LShift"
rewind = "R"
save_state = "F5"
load_state = "F6"

open_debugger = "F12"
debug_step = "F7"
debug_stepback = "F8"
debug_run = "F9"
