ignore-dev-dependencies = true
ignore-build-dependencies = true
accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
]

targets = ["x86_64-unknown-linux-gnu"]
