[package]
name = "gameroy-jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynasmrt = "2.0.0"

gameroy-core = { path = "../core" }
