[env]
# workaround for https://github.com/rust-lang/cargo/issues/3946
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[registries.crates-io]
protocol = "sparse"
