name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - name: Update apt
      run: sudo apt update
    - name: Install depencies
      run: sudo apt-get install libasound2-dev libgtk-3-dev

    - uses: robinraju/release-downloader@v1.5
      with: 
        repository: "c-sp/gameboy-test-roms"
        tag: "v3.2"
        fileName: "gameboy-test-roms-v3.2.zip"

    - name: Unzip test roms
      run: unzip gameboy-test-roms-v3.2.zip -d core/tests/gameboy-test-roms/

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: false

    - name: Run tests
      run: cargo test -p=gameroy-jit -- test_sprite_late test_three --nocapture
