name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - name: Update apt
      run: sudo apt update
    - name: Install depencies
      run: sudo apt-get install libasound2-dev libgtk-3-dev

    - name: Install resvg
      run: cargo install resvg

    - name: Build Native
      run: cargo build --verbose -p gameroy_native

    - uses: robinraju/release-downloader@v1.5
      with: 
        repository: "c-sp/gameboy-test-roms"
        tag: "v3.2"
        fileName: "gameboy-test-roms-v3.2.zip"

    - name: Unzip test roms
      run: unzip gameboy-test-roms-v3.2.zip -d core/tests/gameboy-test-roms/

    - name: Run tests
      run: cargo test --verbose --workspace

  android-build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - run: cd android

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Update apt
      run: sudo apt update
    - name: Install depencies
      run: sudo apt-get install libasound2-dev libgtk-3-dev

    - name: Install android targets
      run: >-
        rustup target install
        aarch64-linux-android
        armv7-linux-androideabi
        i686-linux-android
        x86_64-linux-android

    - name: Install resvg
      run: cargo install resvg
    - name: Install cargo-about
      run: cargo install cargo-about

    - name: Write Keystore.properties
      env:
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      run: echo "$KEYSTORE_PROPERTIES" > keystore.properties

    - name: Write keystore.jks
      env:
        ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
      run: echo $ENCODED_KEYSTORE | base64 -di > keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
